### ISSUE TITLE
Uncaught TypeError: undefined is not a function (

### ISSUE THREAD

**Issue by rionner** [rionner/RESTaurant#1]
Uncaught TypeError: undefined is not a function(anonymous function) @ app.js:9
jQuery.Callbacks.fire @ jquery.js:3094
jQuery.Callbacks.self.fireWith @ jquery.js:3206
jQuery.extend.ready @ jquery.js:3412completed @ jquery.js:3428

CODE: app.js

var app = app || {};

$(document).ready(function(){

  app.foods = new app.FoodCollection({
    model: app.FoodModel
  })

  app.parties = new app.PartyCollection({         <<< error on line 9
    model: app.PartyModel
  })

  app.foodListView = new app.ListView({
    modelView: app.FoodView,
    collection: app.foods,
    el: $('#menu-list')
  })

  app.partyListPainter = new app.ListView({
    modelView: app.PartyView,
    collection: app.parties,
    el: $('#party-list')
  })

  app.foods.fetch();
  app.parties.fetch();

});

**Comment by code-for-coffee** [comment]
Hi Marion,

It looks like you didn't include your PartyCollection file inside of your Index.erb. Line 9 of that error is looking for one:

``` javascript
app.parties = new app.PartyCollection({ 
model: app.PartyModel
})
```

All I found are:

``` html
    <!-- Libraries -->
    <script type='text/javascript' src='/javascripts/lib/jquery.js'></script>
    <script type='text/javascript' src='/javascripts/lib/underscore.js'></script>
    <script type="text/javascript" src='/javascripts/lib/backbone.js'></script>

    <!-- Backbone Models -->
    <script src='/javascripts/models/FoodModel.js'></script>
    <script src='/javascripts/models/PartyModel.js'></script>

    <!-- Backbone Collection -->
    <script src='/javascripts/collections/FoodCollection.js'></script>

    <!-- Application -->
    <script src='/javascripts/app.js'></script>
```

**Comment by code-for-coffee** [comment]
Also - be sure to _close_ this issue if it is fixed. :)
